//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long ID { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Enquiry { get; set; }
        public System.DateTime SentDate { get; set; }
        public bool IsReaded { get; set; }
        public string UserID { get; set; }
    }
}
