//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string ContentHtml { get; set; }
        public bool Status { get; set; }
    }
}
