//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string ShortTitle { get; set; }
        public string MetaTitle { get; set; }
        public string Description { get; set; }
        public string ContentHtml { get; set; }
        public string Images { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string RelatedNewes { get; set; }
        public long CategoryID { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> UpTopNew { get; set; }
        public Nullable<System.DateTime> UpTopHot { get; set; }
        public string RelatedProduct { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
