//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string MetaTitle { get; set; }
        public string Description { get; set; }
        public string Thumb { get; set; }
        public string Images { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public long CategoryID { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public int BrandID { get; set; }
        public bool UpTopHot { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Guarantee { get; set; }
        public string Video { get; set; }
        public string Specification { get; set; }
        public Nullable<long> PercentSale { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
