//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public string Images { get; set; }
        public int Order { get; set; }
        public string GroupID { get; set; }
        public bool Status { get; set; }
    
        public virtual GroupSlide GroupSlide { get; set; }
    }
}
